[package]
name = "fast-utf8"
version = "0.1.0"
edition = "2021"

[features]
stats = []

[[bench]]
name = "vs_std_criterion"
harness = false

[dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }