[package]
name = "fast-utf8"
version = "0.1.0"
edition = "2021"

[[bench]]
name = "vs_std_criterion"
harness = false
bench = false

[dev-dependencies]
criterion = { version = "0.4", features = ["html_reports"] }